<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Report-Introduction" data-toc-modified-id="Report-Introduction-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Report Introduction</a></span></li><li><span><a href="#Background" data-toc-modified-id="Background-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Background</a></span></li><li><span><a href="#Modeling-Assumptions-and-Potential-Issues" data-toc-modified-id="Modeling-Assumptions-and-Potential-Issues-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Modeling Assumptions and Potential Issues</a></span></li><li><span><a href="#Test-design" data-toc-modified-id="Test-design-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Test design</a></span><ul class="toc-item"><li><span><a href="#Creating-the-Testing-and-Training-Datasets" data-toc-modified-id="Creating-the-Testing-and-Training-Datasets-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Creating the Testing and Training Datasets</a></span></li></ul></li><li><span><a href="#Models-Description-and-Assessments" data-toc-modified-id="Models-Description-and-Assessments-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Models Description and Assessments</a></span><ul class="toc-item"><li><span><a href="#Logistic-Regression" data-toc-modified-id="Logistic-Regression-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>Logistic Regression</a></span><ul class="toc-item"><li><span><a href="#Introduction" data-toc-modified-id="Introduction-5.1.1"><span class="toc-item-num">5.1.1&nbsp;&nbsp;</span>Introduction</a></span></li><li><span><a href="#Construction-and-Tuning" data-toc-modified-id="Construction-and-Tuning-5.1.2"><span class="toc-item-num">5.1.2&nbsp;&nbsp;</span>Construction and Tuning</a></span></li><li><span><a href="#Interpretation" data-toc-modified-id="Interpretation-5.1.3"><span class="toc-item-num">5.1.3&nbsp;&nbsp;</span>Interpretation</a></span></li><li><span><a href="#Detailed-assessment" data-toc-modified-id="Detailed-assessment-5.1.4"><span class="toc-item-num">5.1.4&nbsp;&nbsp;</span>Detailed assessment</a></span></li></ul></li><li><span><a href="#Support-Vector-Machines-(SVM)" data-toc-modified-id="Support-Vector-Machines-(SVM)-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>Support Vector Machines (SVM)</a></span><ul class="toc-item"><li><span><a href="#Introduction" data-toc-modified-id="Introduction-5.2.1"><span class="toc-item-num">5.2.1&nbsp;&nbsp;</span>Introduction</a></span></li><li><span><a href="#Construction-and-Tuning" data-toc-modified-id="Construction-and-Tuning-5.2.2"><span class="toc-item-num">5.2.2&nbsp;&nbsp;</span>Construction and Tuning</a></span></li><li><span><a href="#Interpretation" data-toc-modified-id="Interpretation-5.2.3"><span class="toc-item-num">5.2.3&nbsp;&nbsp;</span>Interpretation</a></span></li><li><span><a href="#Detailed-assessment" data-toc-modified-id="Detailed-assessment-5.2.4"><span class="toc-item-num">5.2.4&nbsp;&nbsp;</span>Detailed assessment</a></span></li></ul></li><li><span><a href="#Convoluted-Neural-Network-(CNN)" data-toc-modified-id="Convoluted-Neural-Network-(CNN)-5.3"><span class="toc-item-num">5.3&nbsp;&nbsp;</span>Convoluted Neural Network (CNN)</a></span><ul class="toc-item"><li><span><a href="#Introduction" data-toc-modified-id="Introduction-5.3.1"><span class="toc-item-num">5.3.1&nbsp;&nbsp;</span>Introduction</a></span></li><li><span><a href="#Construction-and-Tuning" data-toc-modified-id="Construction-and-Tuning-5.3.2"><span class="toc-item-num">5.3.2&nbsp;&nbsp;</span>Construction and Tuning</a></span></li><li><span><a href="#Interpretation" data-toc-modified-id="Interpretation-5.3.3"><span class="toc-item-num">5.3.3&nbsp;&nbsp;</span>Interpretation</a></span></li><li><span><a href="#Detailed-assessment" data-toc-modified-id="Detailed-assessment-5.3.4"><span class="toc-item-num">5.3.4&nbsp;&nbsp;</span>Detailed assessment</a></span></li></ul></li></ul></li><li><span><a href="#Summary-of-Modelling" data-toc-modified-id="Summary-of-Modelling-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Summary of Modelling</a></span></li><li><span><a href="#Evaluation-of-Data-Mining-Process" data-toc-modified-id="Evaluation-of-Data-Mining-Process-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Evaluation of Data Mining Process</a></span><ul class="toc-item"><li><span><a href="#Business-success-criteria" data-toc-modified-id="Business-success-criteria-7.1"><span class="toc-item-num">7.1&nbsp;&nbsp;</span>Business success criteria</a></span></li><li><span><a href="#Review-of-project-success:" data-toc-modified-id="Review-of-project-success:-7.2"><span class="toc-item-num">7.2&nbsp;&nbsp;</span>Review of project success:</a></span></li><li><span><a href="#Techniques-and-tools" data-toc-modified-id="Techniques-and-tools-7.3"><span class="toc-item-num">7.3&nbsp;&nbsp;</span>Techniques and tools</a></span></li><li><span><a href="#Future-Work" data-toc-modified-id="Future-Work-7.4"><span class="toc-item-num">7.4&nbsp;&nbsp;</span>Future Work</a></span></li></ul></li><li><span><a href="#References" data-toc-modified-id="References-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>References</a></span></li><li><span><a href="#Background" data-toc-modified-id="Background-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>Background</a></span></li><li><span><a href="#Modeling-assumptions" data-toc-modified-id="Modeling-assumptions-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>Modeling assumptions</a></span></li><li><span><a href="#Test-design" data-toc-modified-id="Test-design-11"><span class="toc-item-num">11&nbsp;&nbsp;</span>Test design</a></span></li><li><span><a href="#Model-description-and-assessment" data-toc-modified-id="Model-description-and-assessment-12"><span class="toc-item-num">12&nbsp;&nbsp;</span>Model description and assessment</a></span><ul class="toc-item"><li><span><a href="#Overview-of-models-produced." data-toc-modified-id="Overview-of-models-produced.-12.1"><span class="toc-item-num">12.1&nbsp;&nbsp;</span>Overview of models produced.</a></span><ul class="toc-item"><li><span><a href="#Type-of-model-and-relationship-to-data-mining-goals" data-toc-modified-id="Type-of-model-and-relationship-to-data-mining-goals-12.1.1"><span class="toc-item-num">12.1.1&nbsp;&nbsp;</span>Type of model and relationship to data mining goals</a></span></li><li><span><a href="#Tuning-and-parameters" data-toc-modified-id="Tuning-and-parameters-12.1.2"><span class="toc-item-num">12.1.2&nbsp;&nbsp;</span>Tuning and parameters</a></span></li><li><span><a href="#Detailed-description-of-the-model-and-any-special-features." data-toc-modified-id="Detailed-description-of-the-model-and-any-special-features.-12.1.3"><span class="toc-item-num">12.1.3&nbsp;&nbsp;</span>Detailed description of the model and any special features.</a></span></li></ul></li><li><span><a href="#Overview-of-assessment-process-and-results,-including-any-deviations-from-the-test-plan.-For-each-model:" data-toc-modified-id="Overview-of-assessment-process-and-results,-including-any-deviations-from-the-test-plan.-For-each-model:-12.2"><span class="toc-item-num">12.2&nbsp;&nbsp;</span>Overview of assessment process and results, including any deviations from the test plan. For each model:</a></span><ul class="toc-item"><li><span><a href="#Detailed-assessment,-including-measurements-such-as-accuracy-and-interpretation-of-behavior" data-toc-modified-id="Detailed-assessment,-including-measurements-such-as-accuracy-and-interpretation-of-behavior-12.2.1"><span class="toc-item-num">12.2.1&nbsp;&nbsp;</span>Detailed assessment, including measurements such as accuracy and interpretation of behavior</a></span></li><li><span><a href="#Insights-into-why-a-certain-modeling-technique-and-certain-parameter-settings-led-to-good/bad-results" data-toc-modified-id="Insights-into-why-a-certain-modeling-technique-and-certain-parameter-settings-led-to-good/bad-results-12.2.2"><span class="toc-item-num">12.2.2&nbsp;&nbsp;</span>Insights into why a certain modeling technique and certain parameter settings led to good/bad results</a></span></li><li><span><a href="#Conclusions-regarding-patterns-in-the-data-(interpretation)" data-toc-modified-id="Conclusions-regarding-patterns-in-the-data-(interpretation)-12.2.3"><span class="toc-item-num">12.2.3&nbsp;&nbsp;</span>Conclusions regarding patterns in the data (interpretation)</a></span></li></ul></li></ul></li><li><span><a href="#Summary-of-conclusions" data-toc-modified-id="Summary-of-conclusions-13"><span class="toc-item-num">13&nbsp;&nbsp;</span>Summary of conclusions</a></span></li><li><span><a href="#Assessment-of-data-mining-results-with-respect-to-business-success-criteria" data-toc-modified-id="Assessment-of-data-mining-results-with-respect-to-business-success-criteria-14"><span class="toc-item-num">14&nbsp;&nbsp;</span>Assessment of data mining results with respect to business success criteria</a></span><ul class="toc-item"><li><span><a href="#Review-of-business-objectives-and-business-success-criteria-(which-may-have-changed-during-and/or-as-a-result-of-data-mining)." data-toc-modified-id="Review-of-business-objectives-and-business-success-criteria-(which-may-have-changed-during-and/or-as-a-result-of-data-mining).-14.1"><span class="toc-item-num">14.1&nbsp;&nbsp;</span>Review of business objectives and business success criteria (which may have changed during and/or as a result of data mining).</a></span><ul class="toc-item"><li><span><a href="#For-each-business-success-criterion:" data-toc-modified-id="For-each-business-success-criterion:-14.1.1"><span class="toc-item-num">14.1.1&nbsp;&nbsp;</span>For each business success criterion:</a></span></li></ul></li><li><span><a href="#Review-of-project-success:" data-toc-modified-id="Review-of-project-success:-14.2"><span class="toc-item-num">14.2&nbsp;&nbsp;</span>Review of project success:</a></span><ul class="toc-item"><li><span><a href="#Has-the-project-achieved-the-original-business-objectives?" data-toc-modified-id="Has-the-project-achieved-the-original-business-objectives?-14.2.1"><span class="toc-item-num">14.2.1&nbsp;&nbsp;</span>Has the project achieved the original business objectives?</a></span></li><li><span><a href="#Are-there-new-business-objectives-to-be-addressed-later-in-the-project-or-in-new-projects?" data-toc-modified-id="Are-there-new-business-objectives-to-be-addressed-later-in-the-project-or-in-new-projects?-14.2.2"><span class="toc-item-num">14.2.2&nbsp;&nbsp;</span>Are there new business objectives to be addressed later in the project or in new projects?</a></span></li></ul></li><li><span><a href="#Review-of-process" data-toc-modified-id="Review-of-process-14.3"><span class="toc-item-num">14.3&nbsp;&nbsp;</span>Review of process</a></span></li><li><span><a href="#List-of-possible-actions:-make-recommendations-regarding-the-next-steps-in-the-project." data-toc-modified-id="List-of-possible-actions:-make-recommendations-regarding-the-next-steps-in-the-project.-14.4"><span class="toc-item-num">14.4&nbsp;&nbsp;</span>List of possible actions: make recommendations regarding the next steps in the project.</a></span></li></ul></li></ul></div>

<h1 class="tocSkip"><center class="tocSkip">Modelling and Evaluation Report</center></h1>
<h1 class="tocSkip"><center class="tocSkip"><i class="tocSkip">Ammar Hasan 150454388</i></center></h1>

In [1]:
# Imports
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
import numpy as np
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import Lasso
from sklearn.metrics import classification_report
import sklearn.metrics as met
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

BASE_PROCESSED_DATA_DIR = '../data/processed'
"""
str: Base processed data directory
"""

PROCESSED_CSV_FILE = BASE_PROCESSED_DATA_DIR + '/processed.csv'
"""
str: HAM1000_metadata.csv metadata file location 
"""
        
# Read datasets in
skin_df = pd.read_csv(PROCESSED_CSV_FILE, index_col=0)

# Code adapted from https://github.com/yuguan1/example-ML-code
## tuning method (5 cv)
def tuning(function, parameters, X_train, y_train):
    print("# Tuning hyper-parameters")
    clf = GridSearchCV(function, parameters, cv=5)
    clf.fit(X_train, y_train)

    print('best parameters:')
    print(clf.best_params_)
    print('-------------------------------------')
    means = clf.cv_results_['mean_test_score']
    stds = clf.cv_results_['std_test_score']

## print metrics (Accuracy, confusion, f1)
def printMetrics(prediction, y_test):
    print('accuracy', met.accuracy_score(y_test, prediction))
    print()
    print(met.confusion_matrix(y_test, prediction))
    print()
    print('f1', met.f1_score(y_test, prediction, average=None))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


## Report Introduction

This report documents the Modelling and Evaluation stages of the CRISP-DM process followed by this project. This stage documents the construction of models and their evaluation - and to a lesser extent the project itself. This include background information about the models, their training, assessment and other evaluations. 

## Background 

As stated in the Business Understanding report the Pigment Skin Diagnosis field use of technology has been growing due critical importance of early detection, and the computerised detection of Skin Lesions is becoming critical. In this project as stated in the criteria of Business Understanding report, the objective of this project is to develop, train and evaluate models (logistic, SVM, neural) to classify skin lesion types and to compare the different models. 

## Modeling Assumptions and Potential Issues

As stated in the Data Understanding report, some issues with the data were recognised:

* Some of the sexes are unknown and the mention of whether these unknown sexes are simply unknown or are non-binary/non-conforming is missing.

* Ground truths were obtained by various methods including expert consensus, which might effect the consistency of the classification.

Hence, we need to assume that both the unknown sexes and the different methods to obtain the ground truth will not have a major impact on the modelling and its analysis.


## Test design

As alluded to before in the background, the following classification models will be built in this project: 

* A neural network - specifically a Convoluted Neural Network 

* Logistic Regression Model 

* A Support Vector Machine 

Models are fitted by using cross validation (10 fold) and if tuning is required 10 fold cross validation is also used to find the optimal parameters. To test models. 

The data used for training and testing is provided from the post process metadata dataset described in the Data Understanding report. 

### Creating the Testing and Training Datasets



								
## Models Description and Assessments
				
### Logistic Regression 

#### Introduction 		

To achieve its classification, Logistic Regression fits a line to separate the data into classes. The line is fitted by minimising the error between line and points by changing the coefficients/weights and the intercept to find the "ideal fit". To minimise the error gradient descent (i.e. loss function optimisation) is used, which updates the parameters (i.e. through partial derivatives) to find a local minimum/maximum. (James et al., 2013)

#### Construction and Tuning 
 

In [2]:
# encode categorical cols using one hot encoding

one_hot_localization = pd.get_dummies(skin_df['localization'])
one_hot_localization.drop('unknown', axis=1, inplace = True)

one_hot_sex = pd.get_dummies(skin_df['sex'])
one_hot_sex.drop('unknown', axis=1, inplace = True)

# Drop old categorical cols and replace with new ones
# drop dx type

skin_df.drop(['dx_type', 'localization', 'sex'], axis = 1, inplace = True)

# Join the encoded dfs
skin_df = skin_df.join(one_hot_localization)
skin_df = skin_df.join(one_hot_sex)

In [4]:
X_train, X_test, y_train, y_test = train_test_split(
    skin_df.drop(['lesion_type_idx', 'lesion_type', 'image_path', 'dx_type'], axis=1),
    skin_df['lesion_type_idx'], test_size=0.2, random_state=42)

scaling = StandardScaler()
scaling.partial_fit(X_test)
X_test = scaling.transform(X_test)

scaling.partial_fit(X_train)
X_train = scaling.transform(X_train)

In [11]:
skin_df.head()

pixel0000_rgb_28_28  pixel0001_rgb_28_28  pixel0002_rgb_28_28  \
0                  192                  153                  193   
1                   25                   14                   30   
2                  192                  138                  153   
3                   38                   19                   30   
4                  158                  113                  139   

   pixel0003_rgb_28_28  pixel0004_rgb_28_28  pixel0005_rgb_28_28  \
0                  195                  155                  192   
1                   68                   48                   75   
2                  200                  145                  163   
3                   95                   59                   72   
4                  194                  144                  174   

   pixel0006_rgb_28_28  pixel0007_rgb_28_28  pixel0008_rgb_28_28  \
0                  197                  154                  185   
1                  123                   93                  126   
2                  201                  142                  160   
3                  143                  103                  119   
4                  215                  162                  191   

   pixel0009_rgb_28_28  ...   foot  genital  hand  lower extremity  scalp  \
0                  202  ...      0        0     0                0      1   
1                  158  ...      0        0     0                0      1   
2                  206  ...      0        0     0                0      1   
3                  171  ...      0        0     0                0      1   
4                  225  ...      0        0     0                0      0   

   trunk  unknown  upper extremity  female  male  
0      0        0                0       0     1  
1      0        0                0       0     1  
2      0        0                0       0     1  
3      0        0                0       0     1  
4      0        0                0       0     1  

[5 rows x 3155 columns]

In [6]:
# Fit and prediction
clf = LogisticRegression(solver='sag', n_jobs = 6).fit(X_train, y_train)
prediction = clf.predict(X_test)
printMetrics(prediction, y_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\sag.py:326: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)


accuracy 0.7483774338492262

[[   9   15   17    1   22    0    5]
 [   0   48   20    0   21    1    3]
 [   5    9  106    0   78    0   30]
 [   0    4    2    1   17    0    4]
 [   3    7   26    1 1259    0   42]
 [   0    0    0    0   13    7    1]
 [   3    2   28    0  122    2   69]]

f1 [0.20224719 0.53932584 0.49648712 0.06451613 0.87735192 0.4516129
 0.36315789]


In [9]:
from sklearn.ensemble import RandomForestClassifier
parameters = [{'max_depth': [20,30],
               'n_estimators': [450, 550]}]

# Tune parameters using 5 fold cross validation 
tuning(RandomForestClassifier(), parameters, X_train, y_train)

# Tuning hyper-parameters
best parameters:
{'max_depth': 20, 'n_estimators': 550}
-------------------------------------


In [8]:
# fit and prediction
optimalDepth = 15
optimalEstimators = 450
clf = RandomForestClassifier(max_depth = optimalDepth, n_estimators = optimalEstimators)
clf.fit(X_train, y_train)
prediction = clf.predict(X_test)

#importances = pd.concat([pd.DataFrame(skin_df.drop(['lesion_type_idx', 'lesion_type'].columns), pd.DataFrame(np.transpose(clf.feature_importances_))], axis = 1)
#print(importances)
# Metrics (predtion vs Test response)
printMetrics(prediction, y_test)

accuracy 0.7149276085871193

[[   6   15   18    0   30    0    0]
 [   2   33    8    0   50    0    0]
 [   4   16   68    0  131    0    9]
 [   0    7    4    0   17    0    0]
 [   0    9   16    0 1302    0   11]
 [   0    0    0    0   21    0    0]
 [   4    1   24    0  174    0   23]]

f1 [0.14117647 0.37931034 0.3715847  0.         0.85014691 0.
 0.17100372]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [ ]:
parameters = [{'kernel': ['rbf'],
                'gamma': [1e-4, 0.01, 0.1, 0.5],
                'C': [1, 10, 100, 1000]}]

# Tune parameters using 5 fold cross validation 
tuning(SVC(), parameters, X_train, y_train)

In [ ]:
# Metrics (predtion vs Test response)
printMetrics(prediction, y_test)


As previously stated, logistic regression fits a line through error minimisation and does not require tuning as the objective is straightforward. 

#### Interpretation		

#### Detailed assessment
										 
### Support Vector Machines (SVM)

#### Introduction 	

Support Vector Machines are another classification model, which is an improvement logistic regression through the addition of two margins for the line which all class points must be behind and the distance to them from the line maximised (again using gradient descent). This ensures that the fairest line out of a set of lines that separate the points is chosen. Support Vector Machines can have the type of margins decided by parameter C, usually divided to either hard one with a large C (narrow with less points out of margin) or one soft with a smaller C (wider with more points out of margin). (Rieck et al., 2012)

To help interpreting non linear data for SVMs, kernels (commonly a Raidial Bias Function (RBF)) transform the data to a higher dimension (kernel trick). Some Kernels take extra parameters, for example RBF takes a gamma parameter which controls the variance or influence of the Support Vector Machine (the higher the gamma the lower the variance) (“RBF SVM parameters — scikit-learn 0.20.2 documentation,” n.d.). 

#### Construction and Tuning 
#### Interpretation					
#### Detailed assessment

### Convoluted Neural Network (CNN)

#### Introduction 		

Convoluted neural networks refer to neural networks where the input image (intermediate images from processing steps) are convolved using kernels in successive layers. As previously stated in the SVM introduction kernels help with interpreting non-linear data 

#### Construction and Tuning 
#### Interpretation					
#### Detailed assessment

	
## Summary of Modelling


## Evaluation of Data Mining Process  


### Business success criteria
				
### Review of project success: 

### Techniques and tools 

### Future Work 


## References 

1. James, G., Witten, D., Hastie, T., Tibshirani, R., 2013. Classification, in: James, G., Witten, D., Hastie, T., Tibshirani, R. (Eds.), An Introduction to Statistical Learning: With Applications in R, Springer Texts in Statistics. Springer New York, New York, NY, pp. 127–173. https://doi.org/10.1007/978-1-4614-7138-7_4

2. Rieck, K., Sonnenburg, S., Mika, S., Schäfer, C., Laskov, P., Tax, D., Müller, K.-R., 2012. Support Vector Machines, in: Gentle, J.E., Härdle, W.K., Mori, Y. (Eds.), Handbook of Computational Statistics: Concepts and Methods, Springer Handbooks of Computational Statistics. Springer Berlin Heidelberg, Berlin, Heidelberg, pp. 883–926. https://doi.org/10.1007/978-3-642-21551-3_30

3. RBF SVM parameters — scikit-learn 0.20.2 documentation [WWW Document], n.d. URL https://scikit-learn.org/stable/auto_examples/svm/plot_rbf_parameters.html (accessed 1.19.19).

 

# Modelling

Serveral modelling techniques are applied and tuned. Related to data peroration (different methods have different requirements)

## Background 

outlines the modeling undertaken and its relationship to the data mining goals.

## Modeling assumptions

explicit assumptions made about the data and any assumptions that are implicit in the modeling technique to be used.

 
## Test design

how the models are built, tested, and evaluated: 
    * Type of model and the training data to be used
	* how the model will be tested or assessed (test data)
					
					
## Model description and assessment

describes the delivered models and overviews the process by which they were produced.

				
### Overview of models produced.

#### Type of model and relationship to data mining goals
					 
#### Tuning and parameters
					
#### Detailed description of the model and any special features.

Description of the model’s behavior and interpretation
							
					
### Overview of assessment process and results, including any deviations from the test plan. For each model:

#### Detailed assessment, including measurements such as accuracy and interpretation of behavior 
										 
#### Insights into why a certain modeling technique and certain parameter settings led to good/bad results 
#### Conclusions regarding patterns in the data (interpretation)
	
			
## Summary of conclusions


	 
# Evaluation: 

Evaluate models and review the steps executed to create them, to be certain the model properly achieves the business objectives. A key objective is to determine if there is some important business issue that has not been sufficiently considered. At the end of this phase, a decision on the use of the data mining results should be reached.

			
## Assessment of data mining results with respect to business success criteria
 
### Review of business objectives and business success criteria (which may have changed during and/or as a result of data mining).
					
#### For each business success criterion:
						
Detailed comparison between success criterion and data mining results
						
Conclusions about achievability of success criterion and suitability of data mining process
				
### Review of project success: 

					
#### Has the project achieved the original business objectives? 
					
#### Are there new business objectives to be addressed later in the project or in new projects?
					
Conclusions for future data mining projects
			
### Review of process

assesses the effectiveness of the project and identifies any factors that may have been overlooked that should be taken into consideration if the project is repeated.
		
### List of possible actions: make recommendations regarding the next steps in the project.