<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Report-Introduction" data-toc-modified-id="Report-Introduction-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Report Introduction</a></span></li><li><span><a href="#Background" data-toc-modified-id="Background-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Background</a></span></li><li><span><a href="#Modeling-Assumptions-and-Potential-Issues" data-toc-modified-id="Modeling-Assumptions-and-Potential-Issues-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Modeling Assumptions and Potential Issues</a></span></li><li><span><a href="#Test-design" data-toc-modified-id="Test-design-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Test design</a></span><ul class="toc-item"><li><span><a href="#Creating-the-Testing-and-Training-Datasets" data-toc-modified-id="Creating-the-Testing-and-Training-Datasets-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Creating the Testing and Training Datasets</a></span><ul class="toc-item"><li><span><a href="#One-Hot-Encoding-and-Minor-Manipulation" data-toc-modified-id="One-Hot-Encoding-and-Minor-Manipulation-4.1.1"><span class="toc-item-num">4.1.1&nbsp;&nbsp;</span>One Hot Encoding and Minor Manipulation</a></span></li><li><span><a href="#Test-Split-and-Scaling" data-toc-modified-id="Test-Split-and-Scaling-4.1.2"><span class="toc-item-num">4.1.2&nbsp;&nbsp;</span>Test Split and Scaling</a></span></li></ul></li></ul></li><li><span><a href="#Models-Description-and-Assessments" data-toc-modified-id="Models-Description-and-Assessments-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Models Description and Assessments</a></span><ul class="toc-item"><li><span><a href="#Logistic-Regression" data-toc-modified-id="Logistic-Regression-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>Logistic Regression</a></span><ul class="toc-item"><li><span><a href="#Introduction" data-toc-modified-id="Introduction-5.1.1"><span class="toc-item-num">5.1.1&nbsp;&nbsp;</span>Introduction</a></span></li><li><span><a href="#Construction-and-Tuning" data-toc-modified-id="Construction-and-Tuning-5.1.2"><span class="toc-item-num">5.1.2&nbsp;&nbsp;</span>Construction and Tuning</a></span></li><li><span><a href="#Interpretation" data-toc-modified-id="Interpretation-5.1.3"><span class="toc-item-num">5.1.3&nbsp;&nbsp;</span>Interpretation</a></span></li><li><span><a href="#Assessment" data-toc-modified-id="Assessment-5.1.4"><span class="toc-item-num">5.1.4&nbsp;&nbsp;</span>Assessment</a></span></li></ul></li><li><span><a href="#Support-Vector-Machines-(SVM)" data-toc-modified-id="Support-Vector-Machines-(SVM)-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>Support Vector Machines (SVM)</a></span><ul class="toc-item"><li><span><a href="#Introduction" data-toc-modified-id="Introduction-5.2.1"><span class="toc-item-num">5.2.1&nbsp;&nbsp;</span>Introduction</a></span></li><li><span><a href="#Construction-and-Tuning" data-toc-modified-id="Construction-and-Tuning-5.2.2"><span class="toc-item-num">5.2.2&nbsp;&nbsp;</span>Construction and Tuning</a></span></li><li><span><a href="#Interpretation" data-toc-modified-id="Interpretation-5.2.3"><span class="toc-item-num">5.2.3&nbsp;&nbsp;</span>Interpretation</a></span></li><li><span><a href="#Detailed-assessment" data-toc-modified-id="Detailed-assessment-5.2.4"><span class="toc-item-num">5.2.4&nbsp;&nbsp;</span>Detailed assessment</a></span></li></ul></li><li><span><a href="#Random-Forest" data-toc-modified-id="Random-Forest-5.3"><span class="toc-item-num">5.3&nbsp;&nbsp;</span>Random Forest</a></span><ul class="toc-item"><li><span><a href="#Introduction" data-toc-modified-id="Introduction-5.3.1"><span class="toc-item-num">5.3.1&nbsp;&nbsp;</span>Introduction</a></span></li><li><span><a href="#Construction-and-Tuning" data-toc-modified-id="Construction-and-Tuning-5.3.2"><span class="toc-item-num">5.3.2&nbsp;&nbsp;</span>Construction and Tuning</a></span></li><li><span><a href="#Interpretation" data-toc-modified-id="Interpretation-5.3.3"><span class="toc-item-num">5.3.3&nbsp;&nbsp;</span>Interpretation</a></span></li><li><span><a href="#Assessment" data-toc-modified-id="Assessment-5.3.4"><span class="toc-item-num">5.3.4&nbsp;&nbsp;</span>Assessment</a></span></li></ul></li></ul></li><li><span><a href="#Summary-of-Modelling" data-toc-modified-id="Summary-of-Modelling-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Summary of Modelling</a></span></li><li><span><a href="#Evaluation-of-Data-Mining-Process" data-toc-modified-id="Evaluation-of-Data-Mining-Process-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Evaluation of Data Mining Process</a></span><ul class="toc-item"><li><span><a href="#Business-success-criteria" data-toc-modified-id="Business-success-criteria-7.1"><span class="toc-item-num">7.1&nbsp;&nbsp;</span>Business success criteria</a></span></li><li><span><a href="#Review-of-project-success:" data-toc-modified-id="Review-of-project-success:-7.2"><span class="toc-item-num">7.2&nbsp;&nbsp;</span>Review of project success:</a></span></li><li><span><a href="#Techniques-and-tools" data-toc-modified-id="Techniques-and-tools-7.3"><span class="toc-item-num">7.3&nbsp;&nbsp;</span>Techniques and tools</a></span></li><li><span><a href="#Future-Work" data-toc-modified-id="Future-Work-7.4"><span class="toc-item-num">7.4&nbsp;&nbsp;</span>Future Work</a></span></li></ul></li><li><span><a href="#References" data-toc-modified-id="References-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>References</a></span></li></ul></div>

<h1 class="tocSkip"><center class="tocSkip">Modelling and Evaluation Report</center></h1>
<h1 class="tocSkip"><center class="tocSkip"><i class="tocSkip">Ammar Hasan 150454388</i></center></h1>

In [31]:
# Imports

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
import numpy as np
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV 
import sklearn.metrics as met
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.ensemble import BaggingClassifier, RandomForestClassifier
from sklearn.multiclass import OneVsRestClassifier
import time


BASE_PROCESSED_DATA_DIR = '../data/processed'
"""
str: Base processed data directory
"""

PROCESSED_CSV_FILE = BASE_PROCESSED_DATA_DIR + '/processed.csv'
"""
str: HAM1000_metadata.csv metadata file location 
"""
        
# Read dataset in
skin_df = pd.read_csv(PROCESSED_CSV_FILE, index_col=0)
"""
pandas.core.frame.DataFrame: final dataset
"""
def tuning(function, parameters, X_train, y_train):
    """
    Used to tune a model using 5 cv
    adapted from https://github.com/yuguan1/example-ML-code
    
    returns best parameters from GridSearchCV
    """
    print("# Tuning hyper-parameters")
    clf = GridSearchCV(function, parameters, cv=5)
    clf.fit(X_train, y_train)

    print('best parameters:')
    print(clf.best_params_)
    print('-------------------------------------')
    return(clf.best_params_)

def printMetrics(prediction, y_test):
    """
    Prints accuracy, confusion and F1 metrics
    
    returns list of accuracy, confusion and F1 metrics
    """
    accuracy = met.accuracy_score(y_test, prediction)
    confusion = met.confusion_matrix(y_test, prediction)
    f1_score = met.f1_score(y_test, prediction, average='weighted')
    
    print('accuracy', accuracy)
    print()
    print(confusion)
    print()
    print('f1', f1_score)
    
    return([accuracy, confusion, f1_score])

## Report Introduction

This report documents the Modelling and Evaluation stages of the CRISP-DM process followed by this project. This stage documents the construction of models and their evaluation - and to a lesser extent the project itself. This include background information about the models, their training, assessment and other evaluations. 

## Background 

As stated in the Business Understanding report the Pigment Skin Diagnosis field use of technology has been growing due critical importance of early detection, and the computerised detection of Skin Lesions is becoming critical. In this project as stated in the criteria of Business Understanding report, the objective of this project is to develop, train and evaluate models (logistic, SVM, neural) to classify skin lesion types and to compare the different models. 

## Modeling Assumptions and Potential Issues

As stated in the Data Understanding report, some issues with the data were recognised:

* Some of the sexes are unknown and the mention of whether these unknown sexes are simply unknown or are non-binary/non-conforming is missing.

* Ground truths were obtained by various methods including expert consensus, which might effect the consistency of the classification.

Hence, we need to assume that both the unknown sexes and the different methods to obtain the ground truth will not have a major impact on the modelling and its analysis.


## Test design

As alluded to before in the background, the following classification models will be built in this project: 

* A neural network - specifically a Convoluted Neural Network 

* Logistic Regression Model 

* A Support Vector Machine 

Models are fitted by using a training data set and if tuning is required 5 fold cross validation is also used to find the optimal parameters. To test models the testing data set is used after the model was trained to evaluate the model (accuracy, confusion, f1 score, etc). The Training and test data is created by splitting the post processed final dataset described in the Data Understanding report in a 50-50 split respectively.

### Creating the Testing and Training Datasets

The final dataset whose creation was described in the Data Preparation report needs minor changes before the modelling begins. In particular, the categorical variables need to be hot coded and the data needs to be divided into model training and model testing samples.

#### One Hot Encoding and Minor Manipulation

In [26]:
# encode categorical cols using one hot encoding

one_hot_localization = pd.get_dummies(skin_df['localization'])
one_hot_localization.drop('unknown', axis=1, inplace = True)

one_hot_sex = pd.get_dummies(skin_df['sex'])
one_hot_sex.drop('unknown', axis=1, inplace = True)

# Drop old categorical cols and replace with new ones
# drop dx type (not needed beyond data understanding)

skin_df.drop(['dx_type', 'localization', 'sex'], axis = 1, inplace = True)

# Join the encoded dfs

skin_df = skin_df.join(one_hot_localization)
skin_df = skin_df.join(one_hot_sex)

Using pandas dummies for categorical variables, localization values are one hot coded using new columns for every value (0 false / 1 true), however one of the columns is dropped a negation of all the other columns represents it. Lastly, the now redundant sex and localization fields are dropped alongside dx_type (no need for analysing diagnosis type beyond Data Understanding).

#### Test Split and Scaling 

In [27]:
# Split the dataset into training and test data in a 50-50 split
# Don't include lesion_types (used for response) and image path (not used yet)

X_train, X_test, y_train, y_test = train_test_split(
    skin_df.drop(['lesion_type_idx', 'lesion_type', 'image_path'], axis=1),
    skin_df['lesion_type_idx'], test_size=0.5, random_state=0)

# scale using a partial fit for speed

scaling = StandardScaler()

scaling.partial_fit(X_test)
X_test = scaling.transform(X_test)

scaling.partial_fit(X_train)
X_train = scaling.transform(X_train)

The training data and the testing data are separated using a 50-50 split respectively, both sets consist of a set of predictors (X) and a response (y). The predictor data has the lesion_type_idx and lesion_type fields removed since they can leak the ground truth. For the response data only the lesion_type_idx field is used since it is sufficient at representing the category of skin lesion (the response / what is being predicted).

To ensure that the impact of predictors is not effected by the measurement scale - which could occur in this dataset due to the variety of predictors, the predictors are scaled using a scaling transform (i.e. with default mean and standard deviation).

### Measurements

The computer used to carry the measurements has the following specifications:
* CPU: i7-7700HQ
* RAM: 8GB
* OS: Windows 10
* GPU: GTX 1060 (notebook)

To evaluate the model the following measurements are taken:
* Fit time: Using the time python library, a timer is started and stopped to measure tuning and fit 
* Prediction time: Using the time python library, a timer is started and stopped to measure the prediction
* Confusion matrix: Using the sklearn metrics library a confusion matrix is printed
* F1 Score: Using the sklearn metrics library a F1 score is calculated using weighted averages


## Models Description and Assessments
				
### Logistic Regression 

#### Introduction 		

To achieve its classification, Logistic Regression fits a line to separate the data into classes. The line is fitted by minimising the error between line and points by changing the coefficients/weights and the intercept to find the "ideal fit". To minimise the error gradient descent (i.e. loss function optimisation) is used, which updates the parameters (i.e. through partial derivatives) to find a local minimum/maximum. (James et al., 2013)

#### Construction and Tuning 

In [9]:
# fit with time measurements, use n_jobs -1 for all cores

log_fit_start = time.time()
clf = LogisticRegression(solver='saga', n_jobs = -1).fit(X_train, y_train)
log_fit_end = time.time()
print('Logistic fit time: ', log_fit_end - log_fit_start)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\sag.py:326: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)


As previously stated, logistic regression fits a line through error minimisation and does not require tuning as the objective is straightforward. The model is simply constructed using a saga solver deployed to 4 threads using sklearn's logistic regression model.

Nonetheless, the constructed model does not seem to converge, this is not that surprising as the fitted line can have many solutions, and sometimes with a large number of predictors this can cause logistic regression to struggle (James et al., 2013).

#### Interpretation		

In [10]:
# form table for coefficients using column names

coefs = pd.concat([pd.DataFrame(skin_df.drop(['lesion_type_idx','lesion_type','image_path'], axis = 1).columns),
                   pd.DataFrame(np.transpose(clf.coef_))], axis = 1)
                 
# print table
                   
print(coefs.iloc[3136:])

                    0         0         1         2         3         4  \
3136              age  0.177739  0.344569  0.576867 -0.050625 -1.046004   
3137          abdomen -0.048107 -0.029776 -0.058278 -0.006311  0.122325   
3138            acral -0.021233 -0.017005 -0.056509 -0.012900  0.084261   
3139             back -0.097517  0.142206 -0.011433 -0.060731 -0.023215   
3140            chest -0.026518  0.136832  0.064297 -0.026464 -0.097892   
3141              ear  0.002943 -0.045324 -0.065051 -0.015759 -0.057547   
3142             face  0.248112  0.107359  0.314902 -0.050211 -0.623524   
3143             foot -0.068091 -0.082843 -0.227369 -0.010350  0.272362   
3144          genital -0.024996 -0.024900  0.014478  0.012730  0.044501   
3145             hand  0.034016 -0.073001  0.044681 -0.029879  0.041418   
3146  lower extremity  0.060830 -0.093954 -0.023619  0.148781 -0.052682   
3147             neck  0.014512  0.058319  0.089373 -0.015234 -0.143925   
3148            scalp  0.

Since as described in the introduction of logistic regression, logistic regression uses a set of coefficients and weights to draw the classification line, it is easy to interpret the model by examining them. However, since there are many predictors we only look at other meta data that is not directly related to the pixels.

Here it can be seen that age is the strongest predictor, in particular with classes 1, 2 and 4 (Basal cell carcinoma, Benign keratosis and Melanocytic nevi respectively), where in classes 1 and 2 age had a positive impact, but in class 4 age had a strong negative one, some of these classes were predicted to have a strong dependence on age in the Data Understanding stage. Age seems to mostly have a positive trend nonetheless - which matches with the observations in the data understanding stage.

When it comes to sex, three classes come to attention, classes 0, 4 and 5 (Actinic keratoses, Melanocytic nevi and melanoma respectively). In class 0, males have a noticiable positive impact which is also seen with class . In class 4 females have a noticiable negative impact. However, in comparison to age, the sexes impact is minor.

For localization, the face seems to have a strong impact when it comes to class 0  (Actinic keratoses), also in class 2 ((Basal cell carcinoma), the face also has a strong impact on a classification in this class while the foot has the opposite effect. However, the classes mostly effected by localization are classes 4 (Melanocytic nevi) where a localization in the face very strongly suggests against a classification to class 4. Overall, localization is the second strongest predictor here.

#### Assessment

In [11]:
# carry prediction with time measurements 
# while recording prediction

log_pred_start = time.time()
prediction = clf.predict(X_test)
log_pred_end = time.time()

log_met = printMetrics(prediction, y_test)
print('Logistic prediction time: ', log_pred_end - log_pred_start)

accuracy 0.7328274760383386

[[  32   24   60    0   32    9    0]
 [  14  106   56    0   74    9    0]
 [   8   28  243    0  193   65    0]
 [   5   13    4    1   38    3    0]
 [   6   23   82    0 3151   94    0]
 [   7   14   97    0  310  132    1]
 [   0   14    5    0   46    4    5]]

f1 [0.27947598 0.44074844 0.44833948 0.03076923 0.87527778 0.30102623
 0.125     ]


We can observe that while the overall accuracy is good, the F1 scores and poor except for class 5 (), this is worrying because as stated before in the business understanding false negative performance is important, and a poor F1 suggests a poor false negative performance as can be seen in the confusion table.

This could be because of the issue observed in the model construction, as there was no convergence due to the large number of predictors perhaps. This might be fixed with the introduction of kernels as explained in the next section.

### Support Vector Machines (SVM)

#### Introduction 	

Support Vector Machines are another classification model, which is an improvement logistic regression through the addition of two margins for the line which all class points must be behind and the distance to them from the line maximised (again using gradient descent). This ensures that the fairest line out of a set of lines that separate the points is chosen. (Rieck et al., 2012)

To help interpreting non linear data for SVMs, kernels (commonly a Raidial Bias Function (RBF)) transform the data to a higher dimension (kernel trick) (Rieck et al., 2012).

#### Construction and Tuning 

In [28]:
# Fit

svm_fit_start = time.time()

n_estimators = 10
clf = OneVsRestClassifier(
    BaggingClassifier(
        SVC(kernel='rbf', random_state=0),
        max_samples=1.0 / n_estimators, n_jobs=-1,
        n_estimators=n_estimators, random_state=0
    ), n_jobs=-1
).fit(X_train, y_train)

svm_fit_start = time.time()
print('SVM fit time: ', svm_fit_end - svm_fit_start)

Due to their high complexity (more on that later) a Bagging Classifier with a One Vs Rest Classifier (OvR) is used to help speed up the execution. The OvR basically creates a classifier for every class of a multi class classification problem to improve efficiency - enables paralysation - (“sklearn.multiclass.OneVsRestClassifier — scikit-learn 0.20.2 documentation,” n.d.).

On the other hand, the Bagging Classifiers which are used by the OneVsRestClassifier works like a Random Decision tree, as it fits multiple classifiers on random subsets of the original dataset which it then aggregates for the final decision (“sklearn.ensemble.BaggingClassifier — scikit-learn 0.20.2 documentation,” n.d.). This ensemble approach reduces the size of the dataset and enables paralysation.

However, this significantly complicates the function and hence tuning is not possible using a GridSearchCV for instance.

#### Interpretation	

Support Vector Machine are more black box like due to their use of kernels, and hence difficult to interpret when it comes to predictor influence - the transformation into higher dimensions makes it difficult to find coefficients. 

#### Detailed assessment

In [30]:
# Prediction 

svm_pred_start = time.time()
prediction = clf.predict(X_test)
svm_pred_end = time.time()

svm_met = printMetrics(prediction, y_test)
print('SVM prediction time: ', svm_pred_end - svm_pred_start)

NameError: name 'confusion_matrix' is not defined


### Random Forest 

#### Introduction 		

A random forest is a modelling technique that makes use of meta estimation through the use of multiple decision trees whose results are combined to form a final decision. The reliance on multiple decision trees helps resolve issues such as overfitting - reduces variance for bias. (“3.2.4.3.1. sklearn.ensemble.RandomForestClassifier — scikit-learn 0.20.2 documentation,” n.d.)

The decision trees themselves are simple non-parametric supervised learning classifiers that make decisions throughout a structure based on entropy of values - high entropy branches and nodes are at higher levels. (“1.10. Decision Trees — scikit-learn 0.20.2 documentation,” n.d.)


#### Construction and Tuning 

In [ ]:
for_fit_start = time.time()

parameters = [{'max_depth': [8,30,45],
               'n_estimators': [150, 450, 550]}]

# Tune parameters using 5 fold cross validation 
best_params = tuning(RandomForestClassifier(n_jobs = -1, random_state=0), parameters, X_train, y_train)


optimalDepth = best_params['max_depth']
optimalEstimators = best_params['n_estimators']
clf = RandomForestClassifier(random_state=0, max_depth = optimalDepth, n_estimators = optimalEstimators)
clf.fit(X_train, y_train)

for_fit_end = time.time()
print('Random Forest fit time: ', for_fit_end - for_fit_start)

The Random Forest Classifier is tuned using a GridSearchCV on two parameters, 'max_depth' and 'n_estimators'. 'max_depth' controls how deep the tree can be constructed - reducing overfitting and simplifies model - and 'n_estimators' controls the number of trees that are created - cuts overfitting for underfitting. 

#### Interpretation					

In [ ]:
importances = pd.concat(
    [pd.DataFrame(skin_df.drop(['lesion_type_idx', 'lesion_type'], axis = 1).columns),
                  pd.DataFrame(np.transpose(clf.feature_importances_))], axis = 1)
print(importances)

(pjh2011, 2018)

#### Assessment

In [ ]:
# Prediction and Assesmenmt

for_pred_start = time.time()
prediction = clf.predict(X_test)
for_pred_end = time.time()

for_met = printMetrics(prediction, y_test)
print('Random Forest prediction time: ', for_pred_end - for_pred_start)

## Summary of Modelling

### Fitting Times

### Prediction Times

### Accuracy 

### F1 Scores 


## Evaluation of Data Mining Process  


### Business success criteria
				
### Review of project success: 

### Techniques and tools 

### Future Work 


## References 

1. James, G., Witten, D., Hastie, T., Tibshirani, R., 2013. Classification, in: James, G., Witten, D., Hastie, T., Tibshirani, R. (Eds.), An Introduction to Statistical Learning: With Applications in R, Springer Texts in Statistics. Springer New York, New York, NY, pp. 127–173. https://doi.org/10.1007/978-1-4614-7138-7_4

2. Rieck, K., Sonnenburg, S., Mika, S., Schäfer, C., Laskov, P., Tax, D., Müller, K.-R., 2012. Support Vector Machines, in: Gentle, J.E., Härdle, W.K., Mori, Y. (Eds.), Handbook of Computational Statistics: Concepts and Methods, Springer Handbooks of Computational Statistics. Springer Berlin Heidelberg, Berlin, Heidelberg, pp. 883–926. https://doi.org/10.1007/978-3-642-21551-3_30

3. sklearn.multiclass.OneVsRestClassifier — scikit-learn 0.20.2 documentation [WWW Document], n.d. URL https://scikit-learn.org/stable/modules/generated/sklearn.multiclass.OneVsRestClassifier.html (accessed 1.24.19).

4. sklearn.ensemble.BaggingClassifier — scikit-learn 0.20.2 documentation [WWW Document], n.d. URL https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.BaggingClassifier.html (accessed 1.24.19).

5. 3.2.4.3.1. sklearn.ensemble.RandomForestClassifier — scikit-learn 0.20.2 documentation [WWW Document], n.d. URL https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html (accessed 1.24.19).

6. 1.10. Decision Trees — scikit-learn 0.20.2 documentation [WWW Document], n.d. URL https://scikit-learn.org/stable/modules/tree.html#tree-classification (accessed 1.24.19).

7. pjh2011, 2018. Contribute to pjh2011/rf_perm_feat_import development by creating an account on GitHub. 